type: "custom:button-card"
show_name: false
show_icon: false
show_label: false
show_state: false
styles:
  grid:
    - grid-template-areas: '"item1 item2"'
    - grid-template-columns: 1fr min-content
    - column-gap: 8px
  card:
    - height: 100%
    - border-radius: "var(--border-radius)"
    - box-shadow: "var(--border-radius)"
    - background: none
    - overflow: visible
    - margin: 0
    - padding: 0
  custom_fields:
    item1: &end
      - justify-self: end
    item2: *end
custom_fields:
  item1:
    card:
      type: "custom:button-card"
      entity: alarm_control_panel.alarmo
      show_name: false
      show_icon: true
      show_label: false
      show_state: false
      tap_action:
        action: more-info
      styles:
        card:
          - height: 30px
          - width: 30px
          - margin: 0
          - padding: 0
          - border-radius: 50px
          - background: "var(--contrast-10)"
          - justify-self: end
        img_cell:
          - height: 100%
        icon:
          - width: 60%
          - color: "var(--contrast-33)"
      state:
        - value: "arming"
          icon: mdi:shield-refresh-outline
          styles:
            card:
              - animation:
                - flash 2s linear infinite
        - value: "armed_home"
          icon: mdi:shield-outline
          styles:
            icon:
              - color: "var(--color-green)"
              - animation:
                - rotate 4s linear infinite
        - value: "armed_away"
          icon: mdi:shield-outline
          styles:
            icon:
              - color: "var(--color-red)"
              - animation:
                - rotate 4s linear infinite
        - value: "disarmed"
          icon: mdi:shield-off-outline
      extra_styles: |
        @keyframes flash {
          0% {opacity: 100%;}
          50% {opacity: 0%;}
          100% {opacity: 100%;}
        }
        @keyframes rotate {
          from {transform: rotateY(-deg);}
          to {transform: rotateY(360deg);}
        }
  item2:
    card:
      type: "custom:button-card"
      entity: input_boolean.theme_mode
      icon: mdi:contrast-circle
      show_name: false
      show_icon: true
      show_label: false
      show_state: false
      styles:
        card:
          - height: 30px
          - width: 30px
          - border-radius: 50px
          - background: "var(--contrast-10)"
          - margin: 0
          - padding: 0
        img_cell:
          - height: 100%
        icon:
          - width: 60%
          - color: "var(--contrast-33)"
